// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDj_lCS3AZMLWKrG-yy4aO2eRqRj6sXAkY',
    appId: '1:980644398020:android:ba5b12e5c0f765b8fa9a91',
    messagingSenderId: '980644398020',
    projectId: 'flutter-firebase-auth-7f723',
    storageBucket: 'flutter-firebase-auth-7f723.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4JCcRgJ4Tz3Ut4AxZQGUW5lhWk3f3-YM',
    appId: '1:980644398020:ios:795766b167b64258fa9a91',
    messagingSenderId: '980644398020',
    projectId: 'flutter-firebase-auth-7f723',
    storageBucket: 'flutter-firebase-auth-7f723.appspot.com',
    androidClientId: '980644398020-3e9bpmfgcpfqk3q6mtl9adnv0qbmfmm0.apps.googleusercontent.com',
    iosClientId: '980644398020-7d5ro8q6n688gveonsbpgfjqjefpa7m2.apps.googleusercontent.com',
    iosBundleId: 'com.example.multiEcommerce',
  );
}
